# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
  name = "co",
  srcs = ["co.cc"],
  hdrs = ["co.h"],
  deps = ["@com_github_google_glog//:glog"],
  visibility = ["//visibility:public"],
)